version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  dockerapi:
    image: eshopperapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7027:1234"   
    restart: always  
    env_file:
      - environments.env

volumes:
  db_volume: